---
- hosts: panos 
  gather_facts: False

  vars:
    - provider:
        username: "{{ admin_username }}"
        password: "{{ admin_password }}"
        ip_address: "{{ ansible_host }}"
    - dns_server: "8.8.8.8"
    - ntp_server_1: "0.us.pool.ntp.org"
    - ntp_server_2: "1.us.pool.ntp.org"
    - timezone: "US/Pacific"
 
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - debug:
        msg: "Debug device: {{ inventory_hostname }} , username: {{ provider.username }} , password: {{ provider.password }} , mgmt_ip: {{ provider.ip_address }}"

    - name: configure ethernet1/1
      panos_interface:
        provider: "{{ provider }}"
        if_name: "ethernet1/1"
        zone_name: "untrust"
        create_default_route: "yes"
        commit: False
      delegate_to: localhost

    - name: configure ethernet1/2
      panos_interface:
        provider: "{{ provider }}"
        if_name: "ethernet1/2"
        zone_name: "trust"
        create_default_route: "no"
        commit: False
      delegate_to: localhost

    - name: set dns and ntp
      panos_mgtconfig:
        provider: "{{ provider }}"
        dns_server_primary: "{{ dns_server }}"
        ntp_server_primary: "{{ ntp_server_1 }}"
        ntp_server_secondary: "{{ ntp_server_2 }}"
        timezone: "{{ timezone }}"
        login_banner: "Secure environment"
        commit: True
      delegate_to: localhost
